### PR TITLE
rename the observedGeneration to observedVersion in resource status

### PR DESCRIPTION
**Pull request by skeeey**

### CODE REVIEW

**Comment by skeeey** [comment]
go clean --testcache
➜  maestro git:(ov) make test
CGO_ENABLED=1 GOEXPERIMENT=boringcrypto go install -ldflags="" ./cmd/maestro
OCM_ENV=testing gotestsum --format short-verbose -- -p 1 -v  \
		./pkg/... \
		./cmd/...
EMPTY pkg/api
EMPTY pkg/api/openapi
EMPTY pkg/api/presenters
EMPTY pkg/auth
EMPTY pkg/client/cloudevents
EMPTY pkg/client/ocm
PASS pkg/config.TestConfigReadStringFile (0.00s)
PASS pkg/config.TestConfigReadIntFile (0.00s)
PASS pkg/config.TestConfigReadBoolFile (0.00s)
PASS pkg/config.TestConfigReadQuotedFile (0.00s)
PASS pkg/config
PASS pkg/controllers.TestControllerFramework (0.00s)
PASS pkg/controllers
EMPTY pkg/dao
EMPTY pkg/dao/mocks
EMPTY pkg/db
EMPTY pkg/db/db_context
EMPTY pkg/db/db_session
EMPTY pkg/db/migrations
EMPTY pkg/db/mocks
EMPTY pkg/db/transaction
PASS pkg/errors.TestErrorFormatting (0.00s)
PASS pkg/errors.TestErrorFind (0.00s)
PASS pkg/errors
EMPTY pkg/handlers
EMPTY pkg/logger
PASS pkg/services.TestSQLTranslation (0.02s)
PASS pkg/services.TestResourceFindByConsumerID (0.00s)
PASS pkg/services.TestValidateNewManifest/validated (0.00s)
PASS pkg/services.TestValidateNewManifest/no_apiVersion (0.00s)
PASS pkg/services.TestValidateNewManifest/no_kind (0.00s)
PASS pkg/services.TestValidateNewManifest/no_name (0.00s)
PASS pkg/services.TestValidateNewManifest/has_generate_name (0.00s)
PASS pkg/services.TestValidateNewManifest/has_resource_version (0.00s)
PASS pkg/services.TestValidateNewManifest/has_deletion_grace_period_seconds (0.00s)
PASS pkg/services.TestValidateNewManifest/wrong_namespace (0.00s)
PASS pkg/services.TestValidateNewManifest/wrong_api_version_(no_version) (0.00s)
PASS pkg/services.TestValidateNewManifest/wrong_api_version_(no_version)#01 (0.00s)
PASS pkg/services.TestValidateNewManifest/wrong_api_version (0.00s)
PASS pkg/services.TestValidateNewManifest (0.00s)
PASS pkg/services.TestValidateUpdateManifest/validated (0.00s)
PASS pkg/services.TestValidateUpdateManifest/apiVersion_mismatch (0.00s)
PASS pkg/services.TestValidateUpdateManifest/kind_mismatch (0.00s)
PASS pkg/services.TestValidateUpdateManifest/name_mismatch (0.00s)
PASS pkg/services.TestValidateUpdateManifest/namespace_mismatch (0.00s)
PASS pkg/services.TestValidateUpdateManifest (0.00s)
PASS pkg/services
EMPTY pkg/util
EMPTY cmd/maestro
EMPTY cmd/maestro/agent
PASS cmd/maestro/environments.TestLoadServices (0.21s)
PASS cmd/maestro/environments
EMPTY cmd/maestro/migrate
EMPTY cmd/maestro/servecmd
EMPTY cmd/maestro/server
EMPTY cmd/maestro/server/logging

DONE 28 tests in 17.004s


make test-integration
CGO_ENABLED=1 GOEXPERIMENT=boringcrypto go install -ldflags="" ./cmd/maestro
OCM_ENV=testing gotestsum --format short-verbose -- -p 1 -ldflags -s -v -timeout 1h  \
			./test/integration
I0111 16:43:25.585786   13600 framework.go:76] Initializing testing environment
I0111 16:43:25.749744   13600 framework.go:161] Using Mock OCM Authz Client
I0111 16:43:25.752146   13600 framework.go:199] Disabling Sentry error reporting
{"level":"info","ts":1704962605.7523441,"logger":"fallback","caller":"v2@v2.0.0-20231030012137-0836a524e995/protocol.go:124","msg":"subscribing to topics: map[sources/clusters/+/specresync:{1 0 false false} sources/maestro-integration/clusters/+/status:{1 0 false false}]"}
I0111 16:43:25.786278   13600 api_server.go:145] Serving without TLS at localhost:8000
I0111 16:43:25.786409   13600 healthcheck_server.go:56] Serving HealthCheck without TLS at localhost:8083
PASS test/integration.TestConsumerGet (0.18s)
PASS test/integration.TestConsumerPost (0.17s)
PASS test/integration.TestConsumerPaging (0.21s)
PASS test/integration.TestControllerRacing (1.67s)
PASS test/integration.TestControllerReconcile (1.18s)
PASS test/integration.TestControllerSync (1.18s)
PASS test/integration.TestResourceGet (0.19s)
PASS test/integration.TestResourcePost (2.20s)
PASS test/integration.TestResourcePatch (0.22s)
PASS test/integration.TestResourcePaging (0.30s)
PASS test/integration.TestResourceListSearch (0.29s)
PASS test/integration.TestUpdateResourceWithRacingRequests (0.34s)
I0111 16:43:33.951523   13600 api_server.go:151] Web server terminated
PASS test/integration

DONE 12 tests in 13.351s

**Comment by clyang82** [comment]
Please upgrade `observedGeneration` to `observedVersion` in README.md file as well. Thanks.

**Comment by skeeey** [comment]
> Please upgrade `observedGeneration` to `observedVersion` in README.md file as well. Thanks.

done

**Review by clyang82 — APPROVED** [review]
LGTM

**Pull request merged**
