### PR TITLE
Using server side update strategy instead of update strategy as ManifestWork update strategy

### PR DESCRIPTION
**Pull request by skeeey**

### CODE REVIEW

**Comment by skeeey** [comment]
make test
CGO_ENABLED=1 GOEXPERIMENT=boringcrypto go install -ldflags="" ./cmd/maestro
OCM_ENV=testing gotestsum --format short-verbose -- -p 1 -v  \
		./pkg/... \
		./cmd/...
PASS pkg/api.TestJSONMapStausToResourceStatus/empty (0.00s)
PASS pkg/api.TestJSONMapStausToResourceStatus/content_status (0.00s)
PASS pkg/api.TestJSONMapStausToResourceStatus/reconcile_status (0.00s)
PASS pkg/api.TestJSONMapStausToResourceStatus/reconcile_status_with_deleted_Condition (0.00s)
PASS pkg/api.TestJSONMapStausToResourceStatus (0.00s)
PASS pkg/api.TestResourceStatusToJSONMap/empty (0.00s)
PASS pkg/api.TestResourceStatusToJSONMap/content_status (0.00s)
PASS pkg/api.TestResourceStatusToJSONMap/reconcile_status (0.00s)
PASS pkg/api.TestResourceStatusToJSONMap/reconcile_status_with_deleted_Condition (0.00s)
PASS pkg/api.TestResourceStatusToJSONMap (0.00s)
PASS pkg/api (cached)
EMPTY pkg/api/openapi
EMPTY pkg/api/presenters
EMPTY pkg/auth
EMPTY pkg/client/cloudevents
EMPTY pkg/client/ocm
PASS pkg/config.TestConfigReadStringFile (0.00s)
PASS pkg/config.TestConfigReadIntFile (0.00s)
PASS pkg/config.TestConfigReadBoolFile (0.00s)
PASS pkg/config.TestConfigReadQuotedFile (0.00s)
PASS pkg/config (cached)
PASS pkg/controllers.TestControllerFramework (0.00s)
PASS pkg/controllers (cached)
EMPTY pkg/dao
EMPTY pkg/dao/mocks
EMPTY pkg/db
EMPTY pkg/db/db_context
EMPTY pkg/db/db_session
EMPTY pkg/db/migrations
EMPTY pkg/db/mocks
EMPTY pkg/db/transaction
PASS pkg/errors.TestErrorFormatting (0.00s)
PASS pkg/errors.TestErrorFind (0.00s)
PASS pkg/errors (cached)
EMPTY pkg/handlers (cached)
EMPTY pkg/logger
PASS pkg/services.TestSQLTranslation (0.02s)
PASS pkg/services.TestResourceFindByConsumerID (0.00s)
PASS pkg/services.TestValidateNewManifest/validated (0.00s)
PASS pkg/services.TestValidateNewManifest/no_apiVersion (0.00s)
PASS pkg/services.TestValidateNewManifest/no_kind (0.00s)
PASS pkg/services.TestValidateNewManifest/no_name (0.00s)
PASS pkg/services.TestValidateNewManifest/has_generate_name (0.00s)
PASS pkg/services.TestValidateNewManifest/has_resource_version (0.00s)
PASS pkg/services.TestValidateNewManifest/has_deletion_grace_period_seconds (0.00s)
PASS pkg/services.TestValidateNewManifest/wrong_namespace (0.00s)
PASS pkg/services.TestValidateNewManifest/wrong_api_version_(no_version) (0.00s)
PASS pkg/services.TestValidateNewManifest/wrong_api_version_(no_version)#01 (0.00s)
PASS pkg/services.TestValidateNewManifest/wrong_api_version (0.00s)
PASS pkg/services.TestValidateNewManifest (0.00s)
PASS pkg/services.TestValidateUpdateManifest/validated (0.00s)
PASS pkg/services.TestValidateUpdateManifest/apiVersion_mismatch (0.00s)
PASS pkg/services.TestValidateUpdateManifest/kind_mismatch (0.00s)
PASS pkg/services.TestValidateUpdateManifest/name_mismatch (0.00s)
PASS pkg/services.TestValidateUpdateManifest/namespace_mismatch (0.00s)
PASS pkg/services.TestValidateUpdateManifest (0.00s)
PASS pkg/services
EMPTY pkg/util
EMPTY cmd/maestro
EMPTY cmd/maestro/agent
PASS cmd/maestro/environments.TestLoadServices (0.32s)
PASS cmd/maestro/environments
EMPTY cmd/maestro/migrate
EMPTY cmd/maestro/servecmd
EMPTY cmd/maestro/server
EMPTY cmd/maestro/server/logging

DONE 38 tests in 8.028s


make test-integration
CGO_ENABLED=1 GOEXPERIMENT=boringcrypto go install -ldflags="" ./cmd/maestro
OCM_ENV=testing gotestsum --format short-verbose -- -p 1 -ldflags -s -v -timeout 1h  \
			./test/integration
I0131 16:18:19.766798   15110 framework.go:76] Initializing testing environment
I0131 16:18:19.944495   15110 framework.go:161] Using Mock OCM Authz Client
I0131 16:18:19.947528   15110 framework.go:199] Disabling Sentry error reporting
{"level":"info","ts":1706689099.947731,"logger":"fallback","caller":"v2@v2.0.0-20231030012137-0836a524e995/protocol.go:124","msg":"subscribing to topics: map[sources/maestro/consumers/+/agentevents:{1 0 false false}]"}
I0131 16:18:19.968536   15110 api_server.go:145] Serving without TLS at localhost:8000
I0131 16:18:19.968695   15110 healthcheck_server.go:56] Serving HealthCheck without TLS at localhost:8083
PASS test/integration.TestConsumerGet (0.17s)
PASS test/integration.TestConsumerPost (0.29s)
PASS test/integration.TestConsumerPaging (0.23s)
PASS test/integration.TestControllerRacing (1.64s)
PASS test/integration.TestControllerReconcile (1.20s)
PASS test/integration.TestControllerSync (1.18s)
PASS test/integration.TestPulseServer (5.23s)
PASS test/integration.TestResourceGet (0.19s)
PASS test/integration.TestResourcePost (2.21s)
PASS test/integration.TestResourcePatch (0.23s)
PASS test/integration.TestResourcePaging (0.42s)
PASS test/integration.TestResourceListSearch (0.31s)
PASS test/integration.TestUpdateResourceWithRacingRequests (0.35s)
I0131 16:18:33.649171   15110 api_server.go:151] Web server terminated
PASS test/integration

DONE 13 tests in 18.233s

make e2e-test
./test/e2e/setup/e2e_teardown.sh
+ command -v kind
+ kind delete cluster --name maestro
Deleting cluster "maestro" ...
...
ginkgo --output-dir="/Users/liuwei/go/src/github.com/openshift-online/maestro/test/e2e/report" --json-report=report.json --junit-report=report.xml \
	/Users/liuwei/go/src/github.com/openshift-online/maestro/test/e2e/pkg -- -consumer_id="2f5cd361-6d17-4a59-9507-9dcc3c2f08cd" \
	-api-server=https://127.0.0.1:30080 -kubeconfig=/Users/liuwei/go/src/github.com/openshift-online/maestro/test/e2e/.kubeconfig
Running Suite: End-to-End Test Suite - /Users/liuwei/go/src/github.com/openshift-online/maestro/test/e2e/pkg

Random Seed: 1706689535

Will run 4 of 4 specs
••••

Ran 4 of 4 Specs in 3.102 seconds
SUCCESS! -- 4 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS

Ginkgo ran 1 suite in 12.98704947s
Test Suite Passed

**Comment by skeeey** [comment]
need to add some e2e test case

**Comment by skeeey** [comment]
make test-integration
CGO_ENABLED=1 GOEXPERIMENT=boringcrypto go install -ldflags="" ./cmd/maestro
OCM_ENV=testing gotestsum --format short-verbose -- -p 1 -ldflags -s -v -timeout 1h  \
			./test/integration
I0201 10:07:18.212953   29905 framework.go:76] Initializing testing environment
I0201 10:07:18.392266   29905 framework.go:161] Using Mock OCM Authz Client
I0201 10:07:18.395044   29905 framework.go:199] Disabling Sentry error reporting
I0201 10:07:18.413744   29905 api_server.go:145] Serving without TLS at localhost:8000
I0201 10:07:18.413888   29905 healthcheck_server.go:56] Serving HealthCheck without TLS at localhost:8083
PASS test/integration.TestConsumerGet (0.18s)
PASS test/integration.TestConsumerPost (0.18s)
PASS test/integration.TestConsumerPaging (0.35s)
PASS test/integration.TestControllerRacing (1.63s)
PASS test/integration.TestControllerReconcile (1.18s)
PASS test/integration.TestControllerSync (1.29s)
PASS test/integration.TestPulseServer (4.18s)
PASS test/integration.TestPulseServerWithStatusDispatcher (4.36s)
PASS test/integration.TestResourceGet (0.22s)
PASS test/integration.TestResourcePost (2.23s)
PASS test/integration.TestResourcePatch (0.35s)
PASS test/integration.TestResourcePaging (0.37s)
PASS test/integration.TestResourceListSearch (0.35s)
PASS test/integration.TestUpdateResourceWithRacingRequests (0.51s)
E0201 10:07:35.834130   29905 logger.go:129]   Unable to get all maestro instances: pq: relation "server_instances" does not exist
I0201 10:07:35.838551   29905 api_server.go:151] Web server terminated
PASS test/integration

DONE 14 tests in 21.684s


make e2e-test
./test/e2e/setup/e2e_teardown.sh
+ command -v kind
+ kind delete cluster --name maestro
Deleting cluster "maestro" ...
+ rm -rf ./test/e2e/setup/.kubeconfig
+ rm -rf ./test/e2e/setup/.consumer_id
+ rm -rf ./test/e2e/setup/.external_host_ip
./test/e2e/setup/e2e_setup.sh
+ command -v kind

...

secret/maestro-agent-mqtt created
serviceaccount/maestro-agent-sa created
ginkgo --output-dir="/Users/liuwei/go/src/github.com/openshift-online/maestro/test/e2e/report" --json-report=report.json --junit-report=report.xml \
	/Users/liuwei/go/src/github.com/openshift-online/maestro/test/e2e/pkg -- -consumer_id="6db806cf-032b-415f-a579-d80109e93198" \
	-api-server=https://127.0.0.1:30080 -kubeconfig=/Users/liuwei/go/src/github.com/openshift-online/maestro/test/e2e/.kubeconfig
Running Suite: End-to-End Test Suite - /Users/liuwei/go/src/github.com/openshift-online/maestro/test/e2e/pkg

Random Seed: 1706753803

Will run 5 of 5 specs
•••••

Ran 5 of 5 Specs in 4.176 seconds
SUCCESS! -- 5 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS

Ginkgo ran 1 suite in 9.258294947s
Test Suite Passed

**Comment by skeeey** [comment]
test to apply a Job to verify the sever side strategy works

/unhold

**Review by qiujian16 — APPROVED** [review]

**Pull request merged**
