### PR TITLE
using consumer name as consumer external id

### PR DESCRIPTION
**Pull request by skeeey**
- Treat the consumer name as a consumer external id, the consumer name
   -  must be unique and not null
   - using RFC 1123 as its format 
   - cannot be updated
   - when creating a consumer, if the name is not specified, the consumer id will be used as name.
- Change the resource fk from  consumer id to consumer name

### CODE REVIEW

**Comment by skeeey** [comment]
maestro git:(eid) make test
CGO_ENABLED=1 GOEXPERIMENT=boringcrypto go install -ldflags="" ./cmd/maestro
OCM_ENV=testing gotestsum --jsonfile-timing-events=/Users/liuwei/go/src/github.com/openshift-online/maestro/unit-test-results.json --format short-verbose -- -p 1 -v  \
		./pkg/... \
		./cmd/...
PASS pkg/api.TestJSONMapStausToResourceStatus/empty (0.00s)
PASS pkg/api.TestJSONMapStausToResourceStatus/content_status (0.00s)
PASS pkg/api.TestJSONMapStausToResourceStatus/reconcile_status (0.00s)
PASS pkg/api.TestJSONMapStausToResourceStatus/reconcile_status_with_deleted_Condition (0.00s)
PASS pkg/api.TestJSONMapStausToResourceStatus (0.00s)
PASS pkg/api.TestResourceStatusToJSONMap/empty (0.00s)
PASS pkg/api.TestResourceStatusToJSONMap/content_status (0.00s)
PASS pkg/api.TestResourceStatusToJSONMap/reconcile_status (0.00s)
PASS pkg/api.TestResourceStatusToJSONMap/reconcile_status_with_deleted_Condition (0.00s)
PASS pkg/api.TestResourceStatusToJSONMap (0.00s)
PASS pkg/api
EMPTY pkg/api/openapi
EMPTY pkg/api/presenters
EMPTY pkg/auth
EMPTY pkg/client/cloudevents
EMPTY pkg/client/ocm
PASS pkg/config.TestConfigReadStringFile (0.00s)
PASS pkg/config.TestConfigReadIntFile (0.00s)
PASS pkg/config.TestConfigReadBoolFile (0.00s)
PASS pkg/config.TestConfigReadQuotedFile (0.00s)
PASS pkg/config
PASS pkg/controllers.TestControllerFramework (0.00s)
PASS pkg/controllers
EMPTY pkg/dao
EMPTY pkg/dao/mocks
EMPTY pkg/db
EMPTY pkg/db/db_context
EMPTY pkg/db/db_session
EMPTY pkg/db/migrations
EMPTY pkg/db/mocks
EMPTY pkg/db/transaction
EMPTY pkg/dispatcher
PASS pkg/errors.TestErrorFormatting (0.00s)
PASS pkg/errors.TestErrorFind (0.00s)
PASS pkg/errors
EMPTY pkg/event
EMPTY pkg/handlers
EMPTY pkg/logger
PASS pkg/services.TestSQLTranslation (0.02s)
PASS pkg/services.TestResourceFindByConsumerID (0.00s)
PASS pkg/services.TestCreateInvalidResource (0.00s)
PASS pkg/services.TestValidateConsumer/validated (0.00s)
PASS pkg/services.TestValidateConsumer/wrong_name (0.00s)
PASS pkg/services.TestValidateConsumer/max_length (0.00s)
PASS pkg/services.TestValidateConsumer (0.00s)
PASS pkg/services.TestValidateNewManifest/validated (0.00s)
PASS pkg/services.TestValidateNewManifest/no_apiVersion (0.00s)
PASS pkg/services.TestValidateNewManifest/no_kind (0.00s)
PASS pkg/services.TestValidateNewManifest/no_name (0.00s)
PASS pkg/services.TestValidateNewManifest/has_generate_name (0.00s)
PASS pkg/services.TestValidateNewManifest/has_resource_version (0.00s)
PASS pkg/services.TestValidateNewManifest/has_deletion_grace_period_seconds (0.00s)
PASS pkg/services.TestValidateNewManifest/wrong_namespace (0.00s)
PASS pkg/services.TestValidateNewManifest/wrong_api_version_(no_version) (0.00s)
PASS pkg/services.TestValidateNewManifest/wrong_api_version_(no_version)#01 (0.00s)
PASS pkg/services.TestValidateNewManifest/wrong_api_version (0.00s)
PASS pkg/services.TestValidateNewManifest (0.00s)
PASS pkg/services.TestValidateUpdateManifest/validated (0.00s)
PASS pkg/services.TestValidateUpdateManifest/apiVersion_mismatch (0.00s)
PASS pkg/services.TestValidateUpdateManifest/kind_mismatch (0.00s)
PASS pkg/services.TestValidateUpdateManifest/name_mismatch (0.00s)
PASS pkg/services.TestValidateUpdateManifest/namespace_mismatch (0.00s)
PASS pkg/services.TestValidateUpdateManifest (0.00s)
PASS pkg/services
EMPTY pkg/util
EMPTY cmd/maestro
EMPTY cmd/maestro/agent
PASS cmd/maestro/environments.TestLoadServices (0.25s)
PASS cmd/maestro/environments
EMPTY cmd/maestro/migrate
EMPTY cmd/maestro/servecmd
EMPTY cmd/maestro/server
EMPTY cmd/maestro/server/logging

DONE 43 tests in 23.447s

./maestro migration
➜  maestro git:(eid) ✗ make test-integration
CGO_ENABLED=1 GOEXPERIMENT=boringcrypto go install -ldflags="" ./cmd/maestro
OCM_ENV=testing gotestsum --jsonfile-timing-events=/Users/liuwei/go/src/github.com/openshift-online/maestro/integration-test-results.json --format short-verbose -- -p 1 -ldflags -s -v -timeout 1h  \
			./test/integration
I0315 20:24:03.388542    9312 framework.go:76] Initializing testing environment
I0315 20:24:03.713107    9312 framework.go:161] Using Mock OCM Authz Client
I0315 20:24:03.715911    9312 framework.go:199] Disabling Sentry error reporting
I0315 20:24:03.812079    9312 grpc_server.go:68] Serving gRPC service without TLS at 8090
I0315 20:24:03.812388    9312 healthcheck_server.go:56] Serving HealthCheck without TLS at 8083
PASS test/integration.TestConsumerGet (0.33s)
PASS test/integration.TestConsumerPost (0.22s)
PASS test/integration.TestConsumerPaging (0.26s)
PASS test/integration.TestControllerRacing (1.96s)
PASS test/integration.TestControllerReconcile (1.31s)
PASS test/integration.TestControllerSync (1.22s)
PASS test/integration.TestPulseServer (5.24s)
PASS test/integration.TestResourceGet (0.34s)
PASS test/integration.TestResourcePost (1.36s)
PASS test/integration.TestResourcePatch (0.38s)
PASS test/integration.TestResourcePaging (0.60s)
PASS test/integration.TestResourceListSearch (0.46s)
PASS test/integration.TestUpdateResourceWithRacingRequests (0.42s)
PASS test/integration.TestResourceFromGRPC (4.46s)
E0315 20:24:22.421351    9312 logger.go:129]   Unable to get all maestro instances: pq: relation "server_instances" does not exist
I0315 20:24:22.424678    9312 api_server.go:157] Web server terminated
PASS test/integration

DONE 14 tests in 33.206s


maestro git:(eid) ✗ make e2e-test
./test/e2e/setup/e2e_teardown.sh
+ command -v kind
+ kind delete cluster --name maestro
Deleting cluster "maestro" ...

Random Seed: 1710505000

Will run 5 of 5 specs
•••••

Ran 5 of 5 Specs in 4.167 seconds
SUCCESS! -- 5 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS

Ginkgo ran 1 suite in 19.264093209s
Test Suite Passed

**Review by morvencao — COMMENTED** [review]
also update openapi.yaml? 
https://github.com/openshift-online/maestro/blob/main/openapi/openapi.yaml#L498

**Comment by skeeey** [comment]
> also update openapi.yaml? https://github.com/openshift-online/maestro/blob/main/openapi/openapi.yaml#L498

done

**Comment by skeeey** [comment]
too many conflicts, close this pr using https://github.com/openshift-online/maestro/pull/63 instead

**Pull request closed without merging**
